### ISSUE TITLE
p6 Confusing Instructions/Results

### ISSUE THREAD

**Issue by hunterwilliams** [MakeSchool-Tutorials/Intro-Conditionals-Swift-Playground#2]
For 15 you get Make School even though the 3 & 5 rule comes after rules for 3 and 5.

However for 39 you get Make due to the 3 rule. I'm not 100% sure if the rules make entire sense or you just want us to match it up to meet the output. Easy to code just not clear on instructions

**Comment by dionlarson** [comment]
Fizz buzz is usually presented out of order (for programmers), the rules are not weighted. I need to modify p6 output to correctly match the rules (and possibly just rewrite the rules). To be honest, I added that page after I decided that fizz buzz is a bit too easy on it's own. Thank you for pointing out the inconsistency.
